[package]
authors = ["Nick Fitzgerald <fitzgen@gmail.com>"]
name = "generational-arena"
version = "0.1.0"

[dependencies]
cfg-if = "0.1.5"

[dev-dependencies]
quickcheck = "0.6.2"

[features]
default = ["std"]
std = []
